apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-name
  region: us-west-2
  
vpc:
  id: "vpc-xxx"
  cidr: "10.10.0.0/16"
  subnets:
    public:
      us-west-2a:
        id: "subnet-xxx"
        cidr: "10.10.1.0/24" 
      us-west-2b:
        id: "subnet-xxx"
        cidr: "10.10.2.0/24" 
      us-west-2c:
        id: "subnet-xxx"
        cidr: "10.10.3.0/24"

managedNodeGroups:
  - name: managed-node-group-name
    labels: { role: general-use }
    instanceType: r5.xlarge
    minsize: 1
    desiredCapacity: 1
    maxsize: 2
    volumeSize: 100
    availabilityZones: ["xx-xxxx-2a", "xx-xxxx-2b", "xx-xxxx-2c"]
    ssh:
      publicKeyName: ssh-key-name
    tags:
      Name: managed-node-group-name
        
        
